### ISSUE TITLE
add common pitfall: iteration + asynchrony

### ISSUE THREAD

**Issue by rosshinkley** [rosshinkley/nightmare-examples#2]

**Comment by Mr0grog** [comment]
A slightly more basic formulation of this: queueing new actions after calling `run` or `then`. Maybe good to start there (easier to see why things go awry) and then show how loops are an easy way to accidentally do that?

**Comment by rosshinkley** [comment]
That's a good idea.  Because I had seen several questions crop up that amounted to a for-loop that used a single Nightmare instance, it was the most prevalent in my mind when I wrote this issue.

**Comment by Mr0grog** [comment]
> I had seen several questions crop up that amounted to a for-loop that used a single Nightmare instance

Oh, totally. While it’s not the most basic way to show the core problem, I think it’s unquestionably the most common way people get themselves into the situation, so it should definitely be specifically covered.
