### ISSUE TITLE
Promise examples should all have a `catch()` call

### ISSUE THREAD

**Issue by Mr0grog** [rosshinkley/nightmare-examples#5]
Insofar as these should all demonstrate good conventions, the promise examples should all end with a `catch` call to surface any errors (the Vo and Co examples using generators are fine because those libraries will bubble up the errors for you if you don’t have a `try... catch` block).

``` js
.catch(function(error) {
  console.error('An error occurred:', error);
});
```

**Comment by rosshinkley** [comment]
Agreed.  :)  I _should_ have been a little more careful in putting the original examples together.
