### ISSUE TITLE
Semantic callbacks example requires Co

### ISSUE THREAD

**Issue by Mr0grog** [rosshinkley/nightmare-examples#7]
The callbacks example starts with a `require` call for Co:

``` js
var Nightmare = require('nightmare'),
  co = require('co'),
  nightmare = Nightmare({
    show: true
  });
```

Guessing that just got left behind from modifying other example docs.

**Comment by rosshinkley** [comment]
Ugh.  Copy/paste failure on my part.  Good eye.
