### ISSUE TITLE
Rename “semantic callbacks” to just “callbacks?”

### ISSUE THREAD

**Issue by Mr0grog** [rosshinkley/nightmare-examples#8]
When I first looked at this, I wondered for a brief moment what “semantic” callbacks were supposed to be. Maybe it would be simpler to just say “callbacks.” Barring that, “simple callbacks,” “Node.js-style callbacks,” or “plain callbacks” all seem like they might be a little more straightforward than “semantic.”

**Comment by rosshinkley** [comment]
Fair enough.  "Callbacks" is probably enough.  Consider it done.
